version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=app
    ports:
      - '5432:5432'
    volumes:
      - app:/var/lib/postgresl/data

  api:
    image: educationmanagementsystemapplication
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app
      - CLIENT_URL
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  app: # named db