server:
  port: 8080

spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app?useSSL=false
    username: appuser
    password: 1234567890
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false

habatoo:
  app:
    jwtSecret: habatooSecretKeyhabatooSecretKeyhabatooSecretKeyhabatooSecretKeyhabatooSecretKeyhabatooSecretKey
    jwtExpirationMs: 100500
    secretKey: 1234567890123456789012345678901234567890
    remoteAddr: 0:0:0:0:0:0:0:1