server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app?useSSL=false
    username: appuser
    password: 1234567890
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

habatoo:
  app:
    jwtSecret: habatooSecretKey
    jwtExpirationMs: 100500